version: '3.8'

services:
  usydrag-devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile

    volumes:
      # Forward Docker socket for containerized development
      - /var/run/docker.sock:/var/run/docker-host.sock 
      # Mount the workspace
      - ../..:/workspaces:cached
      # Cache directories for better performance
      - pip-cache:/home/vscode/.cache/pip
      - playwright-cache:/home/vscode/.cache/ms-playwright
      - huggingface-cache:/home/vscode/.cache/huggingface
      - azure-cache:/home/vscode/.azure

    # Environment variables for USD RAG development
    environment:
      - DOCKER_HOST=unix:///var/run/docker-host.sock
      - PYTHONPATH=/workspaces/${localWorkspaceFolderBasename}
      - PLAYWRIGHT_BROWSERS_PATH=/home/vscode/.cache/ms-playwright
      - HF_HOME=/home/vscode/.cache/huggingface
      - AZURE_CONFIG_DIR=/home/vscode/.azure
      - LANGCHAIN_TRACING_V2=true
      - LANGCHAIN_PROJECT=usyd-rag

    # Keep container running
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity 

    # Enable debugging capabilities
    cap_add:
     - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    # Use "forwardPorts" in devcontainer.json to forward ports locally

volumes:
  pip-cache:
  playwright-cache:
  huggingface-cache:
  azure-cache:
